### ISSUE TITLE
Bug na inclusão de exponencial

### ISSUE THREAD

**Issue by hyoretsu** [gcpeixoto/LVMN#1]
Não sei se a intenção era o usuário estar ciente disso, mas pelo `np.exp` ser uma função, se quisermos usar somente o exponencial, precisaríamos substituir `exp` por `np.exp(1)`, e para elevá-lo a algo, substituir `exp**2` por `np.exp(2)`.

Para tal, precisei separar a identificação de outras funções trigonométricas do exponencial, resultando em:
```
f = re.sub(r"((arc)?(sin|cos|tan)h?|log(10)?|sqrt)", r"np.\1", f)
f = re.sub(r"exp\*\*(\d)", r"np.exp(\1)", f)
f = re.sub(r"exp\*\*(\(.*\))", r"np.exp\1", f)
f = re.sub(r"\bexp\b", "exp(1)", f)
```

Com 3 casos para exponenciação por número, por algo composto (com parêntesis) e exponencial sozinha.

**Comment by gcpeixoto** [comment]
A versão da regex à qual você se refere está vinculada em qual notebook? Salvo engano, as versões existentes nos algoritmos da bisseção e Newton, são capazes de tratar os casos em que o usuário entra com `exp(a)`, para qualquer constante `a`, visto que a substituição do padrão é apenas `exp` por `np.exp`, para incrementar o alias do Numpy.  

Além disso, note que `np.exp**` é incorreto, pois não é a função que é potenciada. `np.exp(a)` é matematicamente equivalente ao número de Euler elevado a `a`, i.e. $e^a$. 

Revise aí...

Qual é o bug, especificamente?

**Comment by hyoretsu** [comment]
Na minha interpretação, ou pelo menos o ideal, era para o usuário escrever `e`, ou `exp` para facilitar o código, e transformar-mos em `np.exp(1)`, ou `e**5`/`exp**5` em `np.exp(5)` automaticamente.

Mas, considerando que o senhor queria que o usuário já estivesse ciente que a exponencial do NumPy é uma função e precisasse que ele escrevesse `exp(5)` na string de entrada, tanto essa quanto a outra issue são inexistentes.

Mas na minha opinião isso derrota um pouco do propósito de não fazer o usuário escrever `np.` para as funções trigonométricas. A meu ver, ambos optamos por usar strings para ser mais fácil do usuário escrever e ficar mais parecido com a notação matemática que estamos acostumados, que não contém exponenciação entre parêntesis nem exp como em
`10x² - 3x + exp(2x)` e `2x² + exp(1)`.

**Comment by gcpeixoto** [comment]
Sim, devemos assumir minimamente que o usuário faça input pela forma funcional `exp(...)` do mesmo modo que faria com `sin`, `cos` ou `log`, de modo a completar o rol de funções transcendentes.

Os argumentos são: 

 i)`e` pode representar uma variável independente, do mesmo modo que `x`, ou `y` ou `z`. Não há necessidade de reservar esse caracter para o propósito de ser $e$;
ii) no caso de o usuário querer representar algo como $e^k, \forall k$, `exp(1)**k` não é irrazoável.
iii) levando em conta a versão _human-readable_ / notação matemática / linguagem natural vs. código, você pode ter razão quanto a ser mais fácil chamar a exponencial, pelo costume ou hábito, mas penso que adicionar mais regex'es para tratar casos particulares seria uma troca de  mais código por menos, porque $e^1$, $e^x$, $e^{y^2 + y}$, etc. são todas expressões cobertas pela forma funcional.  E nesse caso, é uma questão de princípio de programação.
iv) como eu lhe falei... No caso de iii), você teria que tratar o caso `e**` e não `exp**`, porém, `e**` só seria praticável se `e` fosse a representação da variável independente. 

O usuário não precisa escrever `np.`. Isso a regex trata.

Então, estou fechando os issues, mas a discussão foi boa.
