### ISSUE TITLE
Bug na identificação automática de variáveis (sequência de letras maior que 1)

### ISSUE THREAD

**Issue by hyoretsu** [gcpeixoto/LVMN#2]
Sexta anterior, fizemos uma aula sobre implementações em Python para a turma de Tatiana. Como já havia feito na minha implementação em JS, decidi seguir a mesma linha do senhor e aceitar uma string como função para o método, e copiei as linhas de identificação de variável e funções do NumPy (otimizando o RegEx, ficou um tanto mais enxuto).

Porém, ao tentar executar a função `10+50.34/2.34*(1-exp**((-2.34*(x-50.34))/10))`, ele reconhecia a variável como "exp", e não "x"
![image](https://github.com/gcpeixoto/LVMN/assets/20804322/7be2bb60-b91a-455a-8d3d-cbfb27fd93f6)
Mesmo após a substituição para np.exp
![image](https://github.com/gcpeixoto/LVMN/assets/20804322/c92e990a-370f-499c-8a6a-b551a5626797)
e dava um erro "x is not defined" no lambda posteriormente.

Isso ocorreu também com cosseno, então acredito que é relativo a funções trigonométricas sendo usadas com operadores aritméticos, uma vez que ao substituir por `np.exp(resto_dos_numeros)` ele passou a reconhecer apenas o X.

Também devido ao `[\w]*` ele está identificando mais de uma letra como variável (cos, exp). Se retirarmos essa parte, ficando apenas `([a-zA-Z]) ?([\+\-\/*]|$|\))` ele reconhece apenas `p*` e `x*`. Se colocarmos um `\b` (word boundary) antes da primeira parte, ele passa a funcionar como desejado, selecionando apenas variáveis (de um caractére).

------------------

Resumindo: testar ~~funções trigonométricas~~ exponencial com operadores aritméticos, e checar se o RegEx `(\b[a-zA-Z]) ?([\+\-\/*]|$|\))` (ou `(\b[A-z])(\s*|$)[+\-/*)]`, menos legível porém mais enxuto) realmente conserta esse erro.

**Comment by gcpeixoto** [comment]
Leia o outro [comentário](https://github.com/gcpeixoto/LVMN/issues/1#issuecomment-1687289053). `exp**` é  uma sintaxe incorreta.

```python
np.exp**2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for ** or pow(): 'numpy.ufunc' and 'int'
```

**Comment by gcpeixoto** [comment]
Fechando com base no comentário anterior.
